export * from './browser.service';
export { default as browserService } from './browser.service';
export * from './config.service';
export { default as configService } from './config.service';
export * from './date.service';
export { default as dateService } from './date.service';
export * from './desktop.service';
export { default as desktopService } from './desktop.service';
export * from './device.service';
export { default as deviceService } from './device.service';
export * from './drag-and-drop.service';
export * from './env.service';
export { default as envService } from './env.service';
export * from './error.service';
export { default as errorService } from './error.service';
export * from './local-storage.service';
export { default as localStorageService } from './local-storage.service';
export * from './media.service';
export * from './navigation.service';
export { default as navigationService } from './navigation.service';
export * from './operating-system.service';
export { default as operatingSystemService } from './operating-system.service';
export * from './sockets/socket.service';
export { default as RealtimeService } from './sockets/socket.service';
export * from './storage-keys';
export * from './stream.service';
export * from './validation.service';
export { default as validationService } from './validation.service';
export * from './workspace.service';
export { default as workspacesService } from './workspace.service';
export * from './zip.service';
export { default as vpnAuthService } from './vpnAuth.service';
export { default as authService } from './auth.service';
export { default as userService } from './user.service';
export { default as oauthService } from './oauth.service';
