import React from 'react';
import { Container } from 'react-bootstrap';
import NavigationBar from './navigationBar/NavigationBar';
import './Security.css';

class Security extends React.Component {
    constructor(props) {
        super(props);

    }
    
    render() {
        return <div className="Security">
            <NavigationBar navbarItems={<h5>Settings</h5>} showSettingsButton={true} />

            <Container className="security-box">
                <div className="security-title">Two Factor Authentication</div>
                <div className="security-description">Two Factor Authentication provides an extra layer of security for your X Cloud account by requiring a second step of verification when you sign in. In addition to your password, you’ll also need a code generated by the Google Authenticator app on your phone. Follow the steps below to enable 2FA on your account.</div>
                <div className="security-button-container">
                    <button><span className="number">1</span><span className="text">Download App</span></button>
                    <button><span className="number">2</span><span className="text">Scan QR Code</span></button>
                    <button className="off"><span className="number">3</span><span className="text">Backup Key</span></button>
                    <button className="on"><span className="number">4</span><span className="text">Enable</span></button>
                </div>
            </Container>


        </div>;
    }
}

export default Security;